### ISSUE TITLE
Reindex Parallely Based on hour interval

### ISSUE THREAD

**Issue by debraj-manna** [garbin/elasticsearch-reindex#9]
Is it possible to reindex parallely based on hourly interval in some timestamp field (like `created_at`) or using some custom query?

**Comment by garbin** [comment]
Yes, it's entirely possible, the interval controlled through `moment`, so I think it's not a very hard work, see `/bin/elasticsearch-reindex.js` line 48 to line 83. But I'm unable to give more focus in this project currently, because I'm working harder in my new project. So I will not add any new feature in this time, because I have no time to maintain and keep it stable. But I can accept any PR from anyone who can maintain.

**Comment by debraj-manna** [comment]
Thanks Garbin. Let me see.
